name: Deploy to AWS EC2

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Decode PEM key and save to env
        id: decode_key
        run: |
          echo "PRIVATE_KEY<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.EC2_KEY }}" | base64 -d >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ env.PRIVATE_KEY }}
          script: |
            cd node-js-sample
            git pull
            npm install
            pm2 restart all || pm2 start index.js --name "node-app"
